### ISSUE TITLE
Ignore `enum` on a type `boolean` field

### ISSUE THREAD

**Issue by karlvr** [karlvr/openapi-generator-plus#35]
```yml
      IsMailingAddress:
        enum:
          - 'true'
          - 'false'
        type: boolean
```
